# This docker-compose file will set up Elastic APM, Kibana and Elasticsearch containers
# and the apm-server.yml configuration file ensures that APM can talk to Kibana. Once
# the servers are up and running you should be able to browse http://localhost:5601
# and see Kibana running.
# In order to set up the APM dashboards, you will need to run the `./apm-server -setup`
# command on the running apm-server container:
# $ docker-compose up -d
#   Starting elasticsearch_1 ... done
#   Starting kibana_1 ... done
#   Starting apm-server_1 ... done
# $ docker-compose exec apm-server ./apm-server setup
#   Loaded index template
#   Loaded dashboards
# 
# You should now be able to browse http://localhost:5601 and see the APM dashboards in Kibana.

version: "3"
services:
    elasticsearch:
      image: elasticsearch:${ELK_VERSION}
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=true
        - ELASTIC_PASSWORD=pass1223
    kibana:
      image: kibana:${ELK_VERSION}
      ports:
        - "5601:5601"
      links:
        - elasticsearch
      depends_on:
        - elasticsearch
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 #设置访问elasticsearch的地址
        - I18N_LOCALE=zh-CN
        - ELASTICSEARCH_USERNAME=logadmin
        - ELASTICSEARCH_PASSWORD="123456"
    apm-server:
      image: elastic/apm-server:${ELK_VERSION}
      ports:
        - "8200:8200"
      volumes:
        - ./.apm-server.yml:/usr/share/apm-server/apm-server.yml
      depends_on:
        - elasticsearch
      links:
        - elasticsearch
        - kibana
